### ISSUE TITLE
Add images support for conversations with "media attached" (Provide an upload zip option)

### ISSUE THREAD

**Issue by sarnic** [prabhakar267/WA-Reader#28]
Hi,

is it possible to add photos in the reader?

**Comment by prabhakar267** [comment]
@sarnic For images, the user would have to upload the zip file WhatsApp creates 
And i am not sure if WhatsApp maintains an ID mapping between image name inside the text file. It only stores ```<media omitted>``` instead of the image.
Maybe we could come up with some heuristic based on timestamps, but that would require investigation of WhatsApp's logic for the same.

**Comment by rubyAce71697** [comment]
@prabhakar267  The whatsapp maintains the mapping

3/3/18, 9:57 PM - Ramesh GBI OFFSHORE: VID-20180303-WA0001.mp4 (file attached)
3/4/18, 11:12 PM - Ramesh GBI OFFSHORE: IMG-20180304-WA0008.jpg (file attached)
3/4/18, 11:23 PM - Ramesh GBI OFFSHORE: IMG-20180304-WA0009.jpg (file attached)

While emailing the chat, you have to select option "Attach Media"..
Then we would need to upload zip file containing media and text files

**Comment by prabhakar267** [comment]
@rubyAce71697 It actually depends on the OS and app version, since I have seen versions where even after attaching media, txt file has no mapping with the images.
But for the versions where it is possible to have a mapping, I think we can have an **upload zip** option.
I will make a new issue to track it.
