### ISSUE TITLE
Check if file is present in `parse_file` method

### ISSUE THREAD

**Issue by prabhakar267** [prabhakar267/WA-Reader#80]
`parse_file` method gives an error if there is no file present. 
https://github.com/prabhakar267/WA-Reader/blob/a1c927065fde009a1e315c57f25bad1bb4f507f3/app.py#L23

### Task
Add a check to ensure file is present in the request. If not send out the following error message
```"Please upload a file to proceed."```

**Comment by uptoratlen** [comment]
I guess you refer to a empty request.file, right?
a good sample looks like this: `ImmutableMultiDict([('0', <FileStorage: 'whatsapp_chat_en.txt' ('text/plain')>)])`, in case you refer to empty, my best idea is:
in app.py (line 22)
```
file_req = request.files
if len(file_req) == 0:
    response = {
        "success": False,
        "error_message": "Please upload a file to proceed.",
    }
    return jsonify(response), 200
file = file_req['0']
```

I was not able to re-create it so I set the dict to 0 and tested the flow. It worked as expected. But maybe you refer to a different case, otherwise I will add this. If this does not meet your original issue, please add some info on how to re-create this issue.
